### ISSUE TITLE
Easy namespace switching

### ISSUE THREAD

**Issue by robonilha** [unxsist/jet-pilot#1]
Changing between namespaces require choosing the cluster and then choosing the namespace, as someone that needs to change namespaces within the same cluster very often it would be great if they could be separate actions.

Kudos for the app, it's already quite useful!

**Comment by unxsist** [comment]
Hey,

Quick switching should be available through the Command Palette, basically hit Cmd+K (Mac) or Ctrl+K (Win/Linux) and select Switch Context and use your keyboard from there.

I have plans on adding shortcuts to specific commands at a later stage, which should improve this even more :)

**Comment by robonilha** [comment]
Having the command palette is great, but what I mean is to have the option to choose a different namespace without having to choose the context again. Similar to `kubens <different_ns>` in CLI or `:namespace` in k9s.

I suppose it's not everybody that needs switching namespaces often :D

**Comment by unxsist** [comment]
The latest release (1.18.0) should resolve some of your annoyances. First of all it's now possible to switch namespaces through a special Switch Namespace command which allows for quick switching in your current context. 

Next to that I've improvement filtering for commands, so if you would open up the Command Palette and search for things like ctx/context or ns/namespace, this would immediately select context or namespace switching commands.

Let me know if you feel there's more room for improvement before I close out this ticket though!

**Comment by PlugaruT** [comment]
Doesn't seem to work on the latest app version. If I use "Switch namespace" command, it does nothing, it does not allow me to search in the current available list of namespaces.

**Comment by unxsist** [comment]
@PlugaruT it indeed seems broken, I'll make sure to have this fixed in the next release!

**Comment by unxsist** [comment]
:rocket: This issue is resolved in version 1.30.0 of JET Pilot!

**Comment by PlugaruT** [comment]
I can confirm. It works as expected!
