### ISSUE TITLE
Add ability to use alternative kubeconfig

### ISSUE THREAD

**Issue by josegonzalez** [unxsist/jet-pilot#12]
I store my kubeconfigs at separate paths to ensure there isn't overlap between prod/pre-prod clusters. There isn't a way today to select a non-default kubeconfig file, so jet-pilot basically doesn't work.

It would be great if I could specify an alternative path in the settings.

**Comment by josegonzalez** [comment]
Thanks for the update! I'll check this out soon :)

**Comment by unxsist** [comment]
:rocket: This issue is resolved in version 1.27.0 of JET Pilot!
