### ISSUE TITLE
Cannot get external secrets from cluster.

### ISSUE THREAD

**Issue by cogren1** [unxsist/jet-pilot#13]
When I run `kubectl get ExternalSecrets -A` in my shell, I can see a list of ExternalSecret objects on my cluster. However, while I can see other resources on the same cluster in Jet Pilot, including the ClusterSecretStore, I get "No results." for ExternalSecrets.

I switched to a different context and repeated the same actions. I got the exact same results.

I am using "Version 1.27.0 (20240703.151805)". I was actually using the previous version when I discovered this, and I made sure to update and repeat. The results are unchanged.

**Comment by unxsist** [comment]
:rocket: This issue is resolved in version 1.27.1 of JET Pilot!
