### ISSUE TITLE
overflow for long cluster names

### ISSUE THREAD

**Issue by baal-lgln** [unxsist/jet-pilot#14]
Some of our rather long cluster names are leading to a overflow of the name in the GUI:
<img width="203" alt="cluster_name_overflow" src="https://github.com/unxsist/jet-pilot/assets/79303986/24923b5b-7473-4225-9ad7-503a2f3dd159">
Is it possible to show the whole name in the box without overflows/cutting of the text?

**Comment by unxsist** [comment]
:rocket: This issue is resolved in version 1.28.0 of JET Pilot!
