### ISSUE TITLE
Sorting is not working

### ISSUE THREAD

**Issue by greguz** [unxsist/jet-pilot#15]
On Apple Silicon macOS 14.5, with Jet Pilot v1.28.0, by clicking on any column header (tried Pods, Deployments, Jobs, etc) changes the "sorting direction" icon, but won't sort the actual data inside the table.

**Comment by unxsist** [comment]
You might've discovered an unfinished feature 😅. I want to give all listings a bit more love, so I'll take this into account!

**Comment by unxsist** [comment]
:rocket: This issue is resolved in version 1.28.4 of JET Pilot!

**Comment by greguz** [comment]
That was fast!

**Comment by greguz** [comment]
May I also ask for a "fist good issue" for a humble JS developer like me that is also learning some Rust in the spare time? 👀

**Comment by unxsist** [comment]
Appreciate your interest, currently there's no small good first issues but keep an eye on open issues. I'll tag any good first issues as they come in!
