### ISSUE TITLE
Invisible menu bar

### ISSUE THREAD

**Issue by Smidra** [unxsist/jet-pilot#16]
On Ubuntu 24.04 when run either as DEB or AppImage the menubar is strangely invisible.
I could not find any way to modify this in setting. 

![image](https://github.com/user-attachments/assets/339db82f-d09e-424d-bc3f-d612a7eb57db)

PS: Thanks for an awesome project like this.

**Comment by unxsist** [comment]
Strange! Definitely should not look like this, but I haven't been able to test on Ubuntu that much yet. All these different menu systems across OS's is tricky to manage, I'll have a look!

**Comment by Smidra** [comment]
I tested on Fedora and it still does the problem. Its probably related to GNOME title and menu bar.
![image](https://github.com/user-attachments/assets/073e3b3e-20f2-41b5-aab2-09ee171502f5)

**Comment by unxsist** [comment]
:rocket: This issue is resolved in version 1.28.1 of JET Pilot!
