### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by satrox28** [unxsist/jet-pilot#17]
Thanks for creating the great tool. I am not seeing any ARM packages.

Do you have any plans to support the ARM processor.

**Comment by unxsist** [comment]
We have ARM releases for MacOS already. Are you talking about other OS's that support ARM?

**Comment by satrox28** [comment]
> We have ARM releases for MacOS already. Are you talking about other OS's that support ARM?

I am not seeing it here unless which ever doesn't have arch in name is ARM?.

**Comment by unxsist** [comment]
You need to get the aarch64 DMG, which is ARM 💪🏻
