### ISSUE TITLE
AWS EKS Support?

### ISSUE THREAD

**Issue by ctpeter** [unxsist/jet-pilot#18]
AWS EKS Support?

When importing aws eks kubeconfig its not working. Using MFA

**Comment by unxsist** [comment]
I'm using AWS EKS SSO for my job which is working as expected. What's your normal login procedure for kubectl?

**Comment by havardalgrav** [comment]
Using EKS as well and having no issues

**Comment by unxsist** [comment]
Given that I did not receive any other reports around AWS EKS, I'm closing this ticket for now. Feel free to re-open if you still experience issues.
