### ISSUE TITLE
Add nodes details

### ISSUE THREAD

**Issue by seifrajhi** [unxsist/jet-pilot#23]
It would be a good feature to have access to the nodes through  jet-pilot like the other resources in k8s clusters

**Comment by seifrajhi** [comment]
@unxsist , can you please include k8s events ?
```
kubectl get events [optional: --namespace <name>]
```

**Comment by gjanders** [comment]
kubectl events is the newer command introduced around 1.23/1.24 timeframe.

**Comment by unxsist** [comment]
Nodes, namespaces and events will be added in the next feature release

**Comment by unxsist** [comment]
:rocket: This issue is resolved in version 1.30.0 of JET Pilot!
