### ISSUE TITLE
Add node cordon option

### ISSUE THREAD

**Issue by seifrajhi** [unxsist/jet-pilot#34]
**Current Behavior:**
Currently, node management supports `drain` and `uncordon`, but there is no option to **cordon nodes**.

**Proposed Enhancement:**
Add a node `cordon` option to the app to complement the existing  `drain` and `uncordon` features.

**Comment by unxsist** [comment]
You can already cordon a Node via the right-click menu, unless it's already not available for scheduling already, for example when you drained the Node.
