### ISSUE TITLE
[feat] Package for brewers (Linux & macOS)

### ISSUE THREAD

**Issue by silopolis** [unxsist/jet-pilot#36]
It would be great to have it available in our favorite brewery :beer:

Thanks for this project, wishing it a long free life :v:

**Comment by unxsist** [comment]
Just submitted a PR for MacOS: https://github.com/Homebrew/homebrew-cask/pull/190967

**Comment by unxsist** [comment]
PR was accepted, JET Pilot is now available through Homebrew, just run `brew install jet-pilot` and you're good to go! 🎉
